version: '3'
services:
  processo-seletivo-cadastro:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/test
    ports:
      - 8080:8080
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
